[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
action = "Copy"
key = "Insert"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[window.padding]
x = 7
y = 5

[general]
import = ["/home/cz/.config/alacritty/alacritty-theme/themes/pencil_dark.toml"]

[font]
# size = 12
[font.normal]
family = "Source Code Pro"
